name = "ONSUD"
uuid = "a8e3cea5-7096-4966-9abd-27121eb25dc8"
authors = ["Matt Lawless"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
